Add tests for header service
libsv/pulse pull request #89
Opened 2023-04-05 08:23 UTC by pawellewandowski98

Description:
---
- Add tests for header service

2023-04-05 09:33 UTC, wregulski requested changes

2023-04-05 09:33 UTC, wregulski commented on service/header_service_test.go
> +func createFifthHeader() domains.BlockHeader {
Maybe let's merge those two funcs as they are identical, and pass to them correct parameters creating fork and fifth header and then name the variables as:
fork,
fifthHeader

2023-04-05 13:17 UTC, pawellewandowski98 commented on service/chain_service_test.go
> +	var array []domains.BlockHeader = db
It looks weird but after adding pointer to `db *[]domains.BlockHeader` in `header_testrepository` I can not create repository directly from variable with type `testrepository.headerChainFixture`.

2023-04-05 13:17 UTC, pawellewandowski98 commented on service/header_service_test.go
> +}
Ok, I removed this method

2023-04-05 13:17 UTC, pawellewandowski98 commented on internal/tests/testrepository/header_testrepository.go
> +	h1 := findHeader(low, *r.db)
Changed to hLow and hHigh

2023-04-05 13:40 UTC, dorzepowski commented on internal/tests/testrepository/test_repository.go
>  	}
```suggestion
func NewTestRepositories(db []domains.BlockHeader) repository.Repositories {
	return repository.Repositories{
		Headers: NewHeadersTestRepository(&db),
	}
```

2023-04-05 13:40 UTC, dorzepowski commented on service/chain_service_test.go
> +	var array []domains.BlockHeader = db
I've checked that and IMHO to make the usage easier lets remove `*` from [argument to NewTestRepositories](https://github.com/libsv/pulse/pull/89/files#diff-7634bde107366d3e43caa883e2e401717712eb33efb701337bc86e0b8295754bR9) and add `&` in [line with creation of test header repository](https://github.com/libsv/pulse/pull/89/files#diff-7634bde107366d3e43caa883e2e401717712eb33efb701337bc86e0b8295754bR11)

In other words make the change like in https://github.com/libsv/pulse/pull/89/files#r1158536841

2023-04-07 20:24 UTC, sirdeggen approved these changes

2023-04-11 10:41 UTC, wregulski approved these changes

2023-04-11 10:43 UTC, merged